package org.pytorch.demo;

public class Constants {
  public static final String TAG = "PyTorchDemo";

//  public static String[][] IMAGENET_LABEL = new String[][] {
//          {"Bồ Công Anh","boconganh","Bồ công anh hay còn gọi với nhiều cái tên khác như phù công anh, diếp trời, rau mũi cày, diếp dại, mót mét hoặc mũi mác.","Lactuca Indica","Lá bồ công anh là loại lá đơn, mọc cách và có hình trông như một cái mũi mác. Mặt trên có màu nâu sẫm, còn mặt dưới thì cũng có màu nâu nhưng là màu nâu nhạt. Mép lá có răng cưa thưa, hầu như không có cuống."},
//          {"Cúc Bách Nhật","cucbachnhat","Hoa cúc bách nhật là cây thân thảo, cao khoảng 30 – 60cm, mọc thẳng, nhiều cành, phân đốt, có lông; thân non màu xanh, thân già màu tía. Lá cây cúc bách nhật là lá đơn, mọc đối, hình bầu dục, có lông, đầu lá nhọn; cuống lá ngắn, ôm sát thân. Gân chính của lá nổi rõ, màu trắng.","Gomphrena globosa Linn","Bách Nhật là cây thân cỏ, phân cành nhiều, thẳng đứng, có đốt phình rộng, thân và lá có lông trắng. Chiều cao thân: 15 – 50cm mọc đối dạng trái xoan hay bầu dục, kéo dài thành cuống, gốc có bẹ, mặt dưới lá nhiều lông.Thời gian hoa nở từ tháng 6 – 10. Hoa cúc bách nhật hình tròn nở ở đầu cành.Đường kính hoa cúc bách nhật: 2 cm"},
//          {"Cúc Cánh Mối","cuccanhmoi","Hoa thạch thảo có nguồn gốc ở Italy mang những nét đặc trưng của hoa xứ lạnh, đặc biệt là màu sắc tuyệt đẹp vô cùng ấn tượng. Hoa thạch thảo nở quanh năm nhưng chỉ nở rộ vào cuối thu, khi những loài hoa khác bắt đầu tàn úa. Những cánh hoa thạch thảo mỏng manh và mang trong nó những ý nghĩa sâu sắc về tình yêu đôi lứa.","Aster amellus","Là cây thân thảo, sống lâu năm nhờ có thân rễ mọc bò dưới đất, các nhánh nhỏ. Thân cao 15 – 50 cm, đơn hay phân nhánh ít ở ngọn.Lá cây hình lưỡi mác thon dài, hơi có lông mịn, nhọn ở đầu, màu xanh đậm. Các lá ở thân không có cuống mà được gắn thẳng vào trong thânHoa thạch thảo hình tròn, mỏng nhẹ được xếp bởi lớp cánh dài, thuôn nhọn hình trạng giống cánh mối. Vòng hoa đều dài, cánh môi thuôn hẹp, thẳng. Các hoa ở ngoài hình lưỡi dài 1 cm. Hoa giữa hình ống hẹp màu vàng, xếp sát nhau. Màu sắc chủ yếu của thạch thảo là hồng, lam tím, trắng, tím, những cánh hoa xung quanh nhị màu vàng nổi bật.Hoa mọc đơn độc ở đầu các nhánh. Cây ra hoa liên tục quanh nnhưng phổ biến nhất là cuối thu.Thạch thảo cũng có quả dạng bế có mào lông mịn màu vàng."},
//          {"Cúc mai vàng","cucmaivang","Cây hoa mai là loài hoa tượng trưng cho dịp tết đến xuân về. Cùng với những loài hoa khác đua nhau nở rộ, cây mai cũng khoe sắc vàng tươi rực rỡ mỗi độ xuân về.","Ochna integerima","Thân cây xù xì và nhiều cành nhiều nhánh. Cây có tán lá thưa, nếu để phát triển tự do thì cây mọc từ hạt có thể cao tối đa tới 20 – 30m. Gốc cây khá to, và bộ rễ cây mai vàng lồi lõm có độ đâm sâu tới 2 – 3m."},
//          {"Cúc Mặt Trời","cucmattroi","Cúc mặt trời hay còn được gọi là hoa cúc mặt trời, ngay từ tên gọi, chúng ta đã có thể hình dung ra được dáng vẻ của nó, nhỏ nhắn, giống như những tia nắng mặt trời nở rực rỡ. Những bông hoa cúc mặt trời nỏ li ti với những ánh vàng thể hiện sự tinh tế trong cuộc sống, không những thế đây cúng là một trong nhưng loài hoa mang lại may mắn, tiền tài, ý chí vươn lên, mạnh mẽ.","Melampodium paludosu","Cúc Mặt Trời thuộc dạng cây trườn, leo thường được trồng theo bụi và là cây xanh tốt quanh năm. Cây có chiều cao khoảng 20- 40cm, phân làm nhiều cành và nhánh nhỏ. Lá là dạng lá đơn, màu xanh, hình bầu dục, lá có lớp lông mịn. Thân cây tròn, có lớp lông mịn.Hoa tròn nhỏ có màu vàng tươi với nhiều cánh hoa xếp thành một vòng tròn quanh nhị hoa. Những cánh hoa này nhìn như những tia nắng mặt trời ấm áp. Hoa mọc ra từ kẽ lá, cây cho hoa nở quanh năm. Rễ thuộc loại dễ chùm và lan ngang.Hoa tròn nhỏ có màu vàng tươi với nhiều cánh hoa xếp thành một vòng tròn quanh nhị hoa. Những cánh hoa này nhn như những tia nắng mặt trời ấm áp. Hoa mọc ra từ kẽ lá, cây cho hoa nở quanh năm. Rễ thuộc loại dễ chùm và lan ngang."},
//          {"Cúc Nghệ Nâu","cucnghenau","Hoa cúc duyên đơn có nguồn gốc ở Bắc Mỹ và được nhập trồng ở Đà Lạt, thành phố Hồ Chí Minh với sắc hoa vàng đẹp nổi bật, thích hợp để trồng làm cảnh. Ngoài ra, ở Vân Nam (Trung Quốc), lá của loài chuẩn còn được dùng để trị ho do nóng, vô danh thũng độc và ngoại thương xuất huyết.","Coreopsis Tinctoria Nut","Cây thảo mọc hằng năm, cao 0,70-1m. Lá kép với các lá chét hình dải. Cụm hoa đầu to 1,5-5cm ở ngọn, trên cuống dài; hoa ngoài 7-8 cái màu vàng có đốm đậm ở gốc, trên một đế chung màu nâu vàng ánh; hoa ở giữa hình ống màu vàng. Quả bế dẹp, dài, không có mỏ."},
//          {"Cúc Tâm Tư","cuctamtu","Hoa này thực sự trông giống như một sự pha trộn giữa hoa cúc và hoa cúc vạn thọ và nó có cái nhìn của hoa cúc.","Calendula officinalis","Thân thảo, hằng năm hoặc 2 năm, mọc khoảng từ 30 đến 60 cm cao, thẳng, vuông góc, với một mô hình của thân phân nhánh nhị phân đôi khi tam phân, màu xanh lá Cây, mọng nước, thân cành được bao phủ bởi những lông và những lông tuyến, cứng và có một mùi hôi khó chịu."},
//          {"Cẩm Tú Cầu","camtucau","Cẩm tú cầu là một loài hoa đẹp, dạng cây bụi, thân thẳng và ít cành nhánh. Loài hoa này có mặt nhiều ở vùng Bắc Mỹ và các nước châu Á. Hoa cẩm tú cầu có rất nhiều màu sắc như xanh, hồng, hồng tím, trắng… Hoa cẩm tú cầu là loại hoa không có hương thơm.","Hydrangea macrophylla","ẩm tú cầu là cây hoa thân mộc, hoa vô tính, lúc đầu hoa màu trắng sau biến dần thành màu lam hay màu hồng, màu hoa phụ thuộc vào độ PH của đất, cây ưa bóng râm ẩm thấp. Cẩm tú cầu được trồng rộng rãi trong các vườn hoa, vườn cảnh, đặc biệt được dùng làm hoa cưới."},
//          {"Hoa Giấy","hoagiay","Cây hoa giấy là một loại cây leo mạnh mẽ, rất dễ thích nghi và phát triển. ra hoa ở độ tuổi sớm hơn hầu hết các loại. Nó là một loại cây thân gỗ cận nhiệt đới có gai.  Cây hoa giấy mọc hoang dã tự nhiên ở những vùng nhiệt đới và thường được cắt tỉa để làm hàng rào và có một số loại cây lùn gần đây được trồng trong chậu như một loại cây cảnh trong nhà. ","Bougainvillea"," Cây hoa giấy có lá hình bầu dục. Lá của chúng rất thưa thớt và không có gì đặc biệt. Nhưng cây hoa giấy được ưa thích bởi những chùm hoa to, rực rỡ nhiều màu và sự phát triển đáng kinh ngạc. Cây hoa giấy có xu hướng ra hoa quanh năm ở các vùng xích đạo. Ở những nơi khác, cây hoa giấy nở hoa theo mùa, với chu kỳ nở thường từ bốn đến sáu tuần. "},
//          {"Hoa Hồng","hoahong","Cây hoa hồng là một loài thức vật có hoa của chi Rosa, họ Rosaceae. Chúng có hơn ba trăm loài và hàng ngàn giống khác nhau. Thân cây thường có những gai nhọn. Hoa hồng khác nhau về kích thước, hình dạng và màu sắc. Hoa có thể có màu đỏ, hồng, trắng, vàng và xanh. Hầu hết các loài có nguồn gốc từ Châu Á, với số lượng nhỏ có nguồn gốc Châu Âu, Bắc Phi và Tây Bắc Phi.",
//                  "Rose","Hoa hồng thường có 5 cánh hoa giống như hầu hết các loài hoa khác, trừ Rosa sericea thường chỉ có 4 cánh. Mỗi cánh hoa được chia thành hai thùy riêng biệt và thường có màu trắng hoặc hồng, đôi khi còn xuất hiện nhiều màu khác. Bên dưới cánh hoa là 5 hoặc 4 lá đài. Chúng có thể đủ dài để khi nhìn từ trên cao xuống sẽ thấy các điểm màu xanh xen kẽ giữa các cánh hoa."},
//          {"Hồng môn","hongmon","Cây hồng môn là loại cây để bàn có hoa được trồng khá nhiều tại Việt Nam","Anthurium Andraeanum","Cây hồng môn có tuổi thọ cao so với các loại cây cảnh khác. Cây có kích thước nhỏ, thân ngắn và thường mọc thành bụi. Lá cây màu xanh với hình dáng gần giống trái tim dài từ 18-30cm. Lá non có màu nhạt và đậm dần khi trưởng thành. Cuống lá cây dài khoảng 30-40cm và có hình ống trụ."},
//          {"Loa Kèn","loaken","Hoa loa kèn đỏ được xem là loài hoa biểu trưng cho niềm tự hào và kiêu hãnh. Sắc đỏ rực rỡ của loài hoa này còn được yêu thích bởi mang ý nghĩa may mắn, thịnh vượng.","Amaryllis","Hoa loa kèn có hệ tán lá khá phát triển. Lá cây khá mảnh, mọc ra từ củ bên dưới, vươn dài. Hoa mọc ra từ phân thân hành. Hoa không nở riêng lẻ mà mọc thành chùm gồm 2 – 3 bông nở cùng một lúc."},
//          {"Mai Anh Đào","maianhdao","Hoa mai anh đào Đà Lạt có nguồn gốc rất đặc biệt với thân cây thì giống đào mận còn hoa thì lại có năm cánh giống hoa mai. Chính vì nửa mai nửa đào như vậy nên cái tên Mai Anh Đào ra đời.","Prunus cerasoides","Loại cây tầm trung; khi phát triển thuần thục cao 5-7m; đường kính gốc 15-20cm; phân nhánh vừa phải, hình nón, tán lá và cành thưa, không chiếm không gian; lá đơn, nhỏ, mọc cách có răng cưa"},
//          {"Mai Địa Thảo","maidiathao","Hoa mai địa thảo là loài hoa nhỏ xinh, duyên dáng, rực rỡ sắc màu tượng trưng cho vẻ đẹp đằm thắm, kiêu sa của người phụ nữ. Với vẻ phồn thực, loài hoa này chắc chắn sẽ mang đến không khí vui tươi và những may mắn bất ngờ cho gia chủ. ","Impatiens walleriana","Mai địa thảo có cả hoa đơn và hoa kép, hoa đơn có 5 cánh phẳng hình trái tim, hoa kép cánh xoáy nhiều lớp như bông hoa hồng. Điều đặc biệt nhất ở loài hoa này là hoa cực kỳ sai hoa với đa dạng loài màu đơn sắc: trắng, cam, tím, hồng, đỏ, tía,… "},
//          {"Sim Tím","simtim","Hoa cũng được gọi bằng các cái tên mỹ miều khác như hồng sim, cương nhẫm, dương lê hay đào kim nương. Người Việt Nam ta xưa nay quen miệng gọi là hoa sim tím.","Rhodomyrtus tomentosa","Hoa sim thuộc loại cây thân gỗ nhỏ, hay mọc thành từng bụi. Chiều cao rơi vào tầm khoảng 1 – 1.5 m và có cây còn có thể cao lên đến 2 m. Thân cây màu nâu, thường có lớp lông dày và ngắn trên thân. Lớp lông này khá mềm mại đối với cây có thân non."},
//          {"Thanh Anh","thanhanh","Thanh anh thuộc dòng cây bụi, thân cây dạng cỏ có gốc nạc.","Agapanthus Africanus L","Lá cây mọc dày và nhiều từ gốc rễ, xếp thành hai dãy, dạng hình dải gập nhiều hay ít, màu xanh lục thẫm. Lá cây dài khoảng 60 – 80cm, rộng khoảng 4 – 5cm, phiến lá dày, mặt lá nhẵn và bóng, gân chính nổi rõ, mép lá nguyên."},
//          {"Thiên Điểu","thiendieu","Hoa Thiên Điểu (hoa chim thiên đường) là một trong những loài hoa có kiểu dáng và màu sắc độc lạ nhất trên thế giới. Đúng như tên gọi của nó, hoa Thiên Điểu trông giống như một con chim đang tung cánh bay trên bầu trời.","Strelitzia reginae","Những cánh hoa cứng cáp xèo ra như người tráng sĩ khoe sắc vóc mạnh mạnh mẽ của mình. Lá cây có hình trứng hơi thuôn dài với phiến lá rộng, cuống dài, màu xanh hơi giống dạng lá dong nhưng nhỏ và cứng, dầy hơn. Lá cây xanh quanh năm. Các lá kết thành một dạng hình quạt."},
//          {"Tầm Xuân","tamxuan","là một dạng hoa hồng leo có xuất xứ từ các nước châu Âu, khu vực Tây Á và Tây Bắc Phi. Loài hoa này có đặc điểm gần giống với hoa hồng nhưng cánh của hoa tầm xuân lại mỏng hơn, thuộc cây bụi mọc dày, có sức sống mãnh liệt, leo nhanh và cao, thường được trồng để làm nên những hàng rào hoa rực rỡ sắc màu.","Allamanda catharticaL","Cây hoa tầm xuân thường có chiều cao khoảng 1 mét - 5 mét (đôi khi có thể leo cao hơn tới ngọn của các loài cây khác), thân có nhiều gai sắc, nhọn, có móc giúp chúng có thể leo bám dễ dàng. Phần lá kép lông chim có khoảng 5 - 7 lá chét, cho ra hoa có 5 cánh, đường kính khoảng 4 - 6cm. Ban đầu hoa có màu hồng nhạt rồi sau đó chuyển sang màu hồng đậm và cuối cùng là màu trắng. Loài hoa này có thể vừa trang trí, vừa có thể làm bài thuốc chữa bệnh rất tốt, còn nụ tầm xuân chỉ có tác dụng là để trang trí."},
//          {"Xác Pháo Đỏ","xacphaodo","Loài hoa này có nguồn gốc từ khu vực Nam Mỹ, với màu đỏ đặc sắc vốn có, người dân địa phương nơi đây thường thích trồng chúng trong chậu hoặc thành từng thảm lớn ở các công viên hay vườn hoa để trang trí. ","Salvia splendens ker","Hoa xác phảo đỏ nằm trong dòng họ thân bụi, có chiều cao trung bình từ 40 đến 60 cm, có đặc tính phân thành nhiều cành. Lá cây có hình bầu dục hoặc hình trái tim, màu xanh nhạt, mọc đối nhau, đặc biệt thuôn nhọn dần về phía đỉnh. "},
//          {"Đỗ Quyên","doquyen","Cây hoa đỗ quyên còn gọi là cây sơn trà hoa, sơn thạch lựu hay mãn sơn hồng, ánh sơn hồng, báo xuân hoa, sơn thạch lựu","Rosa canina","Cây có dạng thân gỗ khẳng khiu, cao khoảng 0,5 - 2m, dáng cây phong trần, vỏ sần sùi và sống được khá lâu năm"},
//          {"Đỗ Quyên","doquyen","Cây hoa đỗ quyên còn gọi là cây sơn trà hoa, sơn thạch lựu hay mãn sơn hồng, ánh sơn hồng, báo xuân hoa, sơn thạch lựu","Rhododendron spp","Cây có dạng thân gỗ khẳng khiu, cao khoảng 0,5 - 2m, dáng cây phong trần, vỏ sần sùi và sống được khá lâu năm"},
//  };

  public static String[][] IMAGENET_LABEL = new String[][] {
          {"Bồ Công Anh","boconganh","Bồ công anh hay còn gọi với nhiều cái tên khác như phù công anh, diếp trời, rau mũi cày, diếp dại, mót mét hoặc mũi mác.","Lactuca Indica","Lá bồ công anh là loại lá đơn, mọc cách và có hình trông như một cái mũi mác. Mặt trên có màu nâu sẫm, còn mặt dưới thì cũng có màu nâu nhưng là màu nâu nhạt. Mép lá có răng cưa thưa, hầu như không có cuống."},
          {"Cúc Bách Nhật","cucbachnhat","Hoa cúc bách nhật là cây thân thảo, cao khoảng 30 – 60cm, mọc thẳng, nhiều cành, phân đốt, có lông; thân non màu xanh, thân già màu tía. Lá cây cúc bách nhật là lá đơn, mọc đối, hình bầu dục, có lông, đầu lá nhọn; cuống lá ngắn, ôm sát thân. Gân chính của lá nổi rõ, màu trắng.","Gomphrena globosa Linn","Bách Nhật là cây thân cỏ, phân cành nhiều, thẳng đứng, có đốt phình rộng, thân và lá có lông trắng. Chiều cao thân: 15 – 50cm mọc đối dạng trái xoan hay bầu dục, kéo dài thành cuống, gốc có bẹ, mặt dưới lá nhiều lông.Thời gian hoa nở từ tháng 6 – 10. Hoa cúc bách nhật hình tròn nở ở đầu cành.Đường kính hoa cúc bách nhật: 2 cm"},
          {"Cúc Cánh Mối","cuccanhmoi","Hoa thạch thảo có nguồn gốc ở Italy mang những nét đặc trưng của hoa xứ lạnh, đặc biệt là màu sắc tuyệt đẹp vô cùng ấn tượng. Hoa thạch thảo nở quanh năm nhưng chỉ nở rộ vào cuối thu, khi những loài hoa khác bắt đầu tàn úa. Những cánh hoa thạch thảo mỏng manh và mang trong nó những ý nghĩa sâu sắc về tình yêu đôi lứa.","Aster amellus","Là cây thân thảo, sống lâu năm nhờ có thân rễ mọc bò dưới đất, các nhánh nhỏ. Thân cao 15 – 50 cm, đơn hay phân nhánh ít ở ngọn.Lá cây hình lưỡi mác thon dài, hơi có lông mịn, nhọn ở đầu, màu xanh đậm. Các lá ở thân không có cuống mà được gắn thẳng vào trong thânHoa thạch thảo hình tròn, mỏng nhẹ được xếp bởi lớp cánh dài, thuôn nhọn hình trạng giống cánh mối. Vòng hoa đều dài, cánh môi thuôn hẹp, thẳng. Các hoa ở ngoài hình lưỡi dài 1 cm. Hoa giữa hình ống hẹp màu vàng, xếp sát nhau. Màu sắc chủ yếu của thạch thảo là hồng, lam tím, trắng, tím, những cánh hoa xung quanh nhị màu vàng nổi bật.Hoa mọc đơn độc ở đầu các nhánh. Cây ra hoa liên tục quanh nnhưng phổ biến nhất là cuối thu.Thạch thảo cũng có quả dạng bế có mào lông mịn màu vàng."},
          {"Cúc Mặt Trời","cucmattroi","Cúc mặt trời hay còn được gọi là hoa cúc mặt trời, ngay từ tên gọi, chúng ta đã có thể hình dung ra được dáng vẻ của nó, nhỏ nhắn, giống như những tia nắng mặt trời nở rực rỡ. Những bông hoa cúc mặt trời nỏ li ti với những ánh vàng thể hiện sự tinh tế trong cuộc sống, không những thế đây cúng là một trong nhưng loài hoa mang lại may mắn, tiền tài, ý chí vươn lên, mạnh mẽ.","Melampodium paludosu","Cúc Mặt Trời thuộc dạng cây trườn, leo thường được trồng theo bụi và là cây xanh tốt quanh năm. Cây có chiều cao khoảng 20- 40cm, phân làm nhiều cành và nhánh nhỏ. Lá là dạng lá đơn, màu xanh, hình bầu dục, lá có lớp lông mịn. Thân cây tròn, có lớp lông mịn.Hoa tròn nhỏ có màu vàng tươi với nhiều cánh hoa xếp thành một vòng tròn quanh nhị hoa. Những cánh hoa này nhìn như những tia nắng mặt trời ấm áp. Hoa mọc ra từ kẽ lá, cây cho hoa nở quanh năm. Rễ thuộc loại dễ chùm và lan ngang.Hoa tròn nhỏ có màu vàng tươi với nhiều cánh hoa xếp thành một vòng tròn quanh nhị hoa. Những cánh hoa này nhn như những tia nắng mặt trời ấm áp. Hoa mọc ra từ kẽ lá, cây cho hoa nở quanh năm. Rễ thuộc loại dễ chùm và lan ngang."},
          {"Cúc Nghệ Nâu","cucnghenau","Hoa cúc duyên đơn có nguồn gốc ở Bắc Mỹ và được nhập trồng ở Đà Lạt, thành phố Hồ Chí Minh với sắc hoa vàng đẹp nổi bật, thích hợp để trồng làm cảnh. Ngoài ra, ở Vân Nam (Trung Quốc), lá của loài chuẩn còn được dùng để trị ho do nóng, vô danh thũng độc và ngoại thương xuất huyết.","Coreopsis Tinctoria Nut","Cây thảo mọc hằng năm, cao 0,70-1m. Lá kép với các lá chét hình dải. Cụm hoa đầu to 1,5-5cm ở ngọn, trên cuống dài; hoa ngoài 7-8 cái màu vàng có đốm đậm ở gốc, trên một đế chung màu nâu vàng ánh; hoa ở giữa hình ống màu vàng. Quả bế dẹp, dài, không có mỏ."},
          {"Cúc Tâm Tư","cuctamtu","Hoa này thực sự trông giống như một sự pha trộn giữa hoa cúc và hoa cúc vạn thọ và nó có cái nhìn của hoa cúc.","Calendula officinalis","Thân thảo, hằng năm hoặc 2 năm, mọc khoảng từ 30 đến 60 cm cao, thẳng, vuông góc, với một mô hình của thân phân nhánh nhị phân đôi khi tam phân, màu xanh lá Cây, mọng nước, thân cành được bao phủ bởi những lông và những lông tuyến, cứng và có một mùi hôi khó chịu."},
          {"Cúc mai vàng","cucmaivang","Cây hoa mai là loài hoa tượng trưng cho dịp tết đến xuân về. Cùng với những loài hoa khác đua nhau nở rộ, cây mai cũng khoe sắc vàng tươi rực rỡ mỗi độ xuân về.","Ochna integerima","Thân cây xù xì và nhiều cành nhiều nhánh. Cây có tán lá thưa, nếu để phát triển tự do thì cây mọc từ hạt có thể cao tối đa tới 20 – 30m. Gốc cây khá to, và bộ rễ cây mai vàng lồi lõm có độ đâm sâu tới 2 – 3m."},
          {"Cẩm Tú Cầu","camtucau","Cẩm tú cầu là một loài hoa đẹp, dạng cây bụi, thân thẳng và ít cành nhánh. Loài hoa này có mặt nhiều ở vùng Bắc Mỹ và các nước châu Á. Hoa cẩm tú cầu có rất nhiều màu sắc như xanh, hồng, hồng tím, trắng… Hoa cẩm tú cầu là loại hoa không có hương thơm.","Hydrangea macrophylla","ẩm tú cầu là cây hoa thân mộc, hoa vô tính, lúc đầu hoa màu trắng sau biến dần thành màu lam hay màu hồng, màu hoa phụ thuộc vào độ PH của đất, cây ưa bóng râm ẩm thấp. Cẩm tú cầu được trồng rộng rãi trong các vườn hoa, vườn cảnh, đặc biệt được dùng làm hoa cưới."},
          {"Hoa Giấy","hoagiay","Cây hoa giấy là một loại cây leo mạnh mẽ, rất dễ thích nghi và phát triển. ra hoa ở độ tuổi sớm hơn hầu hết các loại. Nó là một loại cây thân gỗ cận nhiệt đới có gai.  Cây hoa giấy mọc hoang dã tự nhiên ở những vùng nhiệt đới và thường được cắt tỉa để làm hàng rào và có một số loại cây lùn gần đây được trồng trong chậu như một loại cây cảnh trong nhà. ","Bougainvillea"," Cây hoa giấy có lá hình bầu dục. Lá của chúng rất thưa thớt và không có gì đặc biệt. Nhưng cây hoa giấy được ưa thích bởi những chùm hoa to, rực rỡ nhiều màu và sự phát triển đáng kinh ngạc. Cây hoa giấy có xu hướng ra hoa quanh năm ở các vùng xích đạo. Ở những nơi khác, cây hoa giấy nở hoa theo mùa, với chu kỳ nở thường từ bốn đến sáu tuần. "},
          {"Hoa Hồng","hoahong","Cây hoa hồng là một loài thức vật có hoa của chi Rosa, họ Rosaceae. Chúng có hơn ba trăm loài và hàng ngàn giống khác nhau. Thân cây thường có những gai nhọn. Hoa hồng khác nhau về kích thước, hình dạng và màu sắc. Hoa có thể có màu đỏ, hồng, trắng, vàng và xanh. Hầu hết các loài có nguồn gốc từ Châu Á, với số lượng nhỏ có nguồn gốc Châu Âu, Bắc Phi và Tây Bắc Phi.",
                  "Rose","Hoa hồng thường có 5 cánh hoa giống như hầu hết các loài hoa khác, trừ Rosa sericea thường chỉ có 4 cánh. Mỗi cánh hoa được chia thành hai thùy riêng biệt và thường có màu trắng hoặc hồng, đôi khi còn xuất hiện nhiều màu khác. Bên dưới cánh hoa là 5 hoặc 4 lá đài. Chúng có thể đủ dài để khi nhìn từ trên cao xuống sẽ thấy các điểm màu xanh xen kẽ giữa các cánh hoa."},
          {"Hoa Lan","hoalan","Tên gọi hoa lan từ xa xưa đã gắn với truyền thuyết về cô thiếu nữ xinh đẹp, hiếu thuận nguyện cải trang thành nam nhi thay cha già tòng quân đánh giặc.","Magnoliaceae","Trong phong thủy phương Đông, trồng hoa lan trước nhà giúp mang lại nhiều vượng khí cho ngôi nhà, giúp gia chủ tăng khả năng thăng tiến trong công việc."},
          {"Huỳnh Anh","huynhanh","Hoa huỳnh anh có vẻ đẹp giản dị không độc đáo như các loại hoa leo khác, nhưng hoa huỳnh anh vẫn rất được ưa chuộm vì hoa dễ trồng và chăm sóc, cây ưa nắng và đã trồng được rất nhiều trên mọi địa phương.","Allamanda catharticaL","Cây Huỳnh anh thuộc dạng cây gỗ, thân leo, cành nhánh dài mềm, thân cành có nhựa mủ màu trắng. Lá đơn, mọc đối, có màu xanh sáng bóng, mềm, mỏng, khi còn non, chúng thường có màu xanh pha hồng."},
          {"Hồng môn","hongmon","Cây hồng môn là loại cây để bàn có hoa được trồng khá nhiều tại Việt Nam","Anthurium Andraeanum","Cây hồng môn có tuổi thọ cao so với các loại cây cảnh khác. Cây có kích thước nhỏ, thân ngắn và thường mọc thành bụi. Lá cây màu xanh với hình dáng gần giống trái tim dài từ 18-30cm. Lá non có màu nhạt và đậm dần khi trưởng thành. Cuống lá cây dài khoảng 30-40cm và có hình ống trụ."},
          {"Loa Kèn","loaken","Hoa loa kèn đỏ được xem là loài hoa biểu trưng cho niềm tự hào và kiêu hãnh. Sắc đỏ rực rỡ của loài hoa này còn được yêu thích bởi mang ý nghĩa may mắn, thịnh vượng.","Amaryllis","Hoa loa kèn có hệ tán lá khá phát triển. Lá cây khá mảnh, mọc ra từ củ bên dưới, vươn dài. Hoa mọc ra từ phân thân hành. Hoa không nở riêng lẻ mà mọc thành chùm gồm 2 – 3 bông nở cùng một lúc."},
          {"Mai Anh Đào","maianhdao","Hoa mai anh đào Đà Lạt có nguồn gốc rất đặc biệt với thân cây thì giống đào mận còn hoa thì lại có năm cánh giống hoa mai. Chính vì nửa mai nửa đào như vậy nên cái tên Mai Anh Đào ra đời.","Prunus cerasoides","Loại cây tầm trung; khi phát triển thuần thục cao 5-7m; đường kính gốc 15-20cm; phân nhánh vừa phải, hình nón, tán lá và cành thưa, không chiếm không gian; lá đơn, nhỏ, mọc cách có răng cưa"},
          {"Mai Địa Thảo","maidiathao","Hoa mai địa thảo là loài hoa nhỏ xinh, duyên dáng, rực rỡ sắc màu tượng trưng cho vẻ đẹp đằm thắm, kiêu sa của người phụ nữ. Với vẻ phồn thực, loài hoa này chắc chắn sẽ mang đến không khí vui tươi và những may mắn bất ngờ cho gia chủ. ","Impatiens walleriana","Mai địa thảo có cả hoa đơn và hoa kép, hoa đơn có 5 cánh phẳng hình trái tim, hoa kép cánh xoáy nhiều lớp như bông hoa hồng. Điều đặc biệt nhất ở loài hoa này là hoa cực kỳ sai hoa với đa dạng loài màu đơn sắc: trắng, cam, tím, hồng, đỏ, tía,… "},
          {"Sim Tím","simtim","Hoa cũng được gọi bằng các cái tên mỹ miều khác như hồng sim, cương nhẫm, dương lê hay đào kim nương. Người Việt Nam ta xưa nay quen miệng gọi là hoa sim tím.","Rhodomyrtus tomentosa","Hoa sim thuộc loại cây thân gỗ nhỏ, hay mọc thành từng bụi. Chiều cao rơi vào tầm khoảng 1 – 1.5 m và có cây còn có thể cao lên đến 2 m. Thân cây màu nâu, thường có lớp lông dày và ngắn trên thân. Lớp lông này khá mềm mại đối với cây có thân non."},
          {"Thanh Anh","thanhanh","Thanh anh thuộc dòng cây bụi, thân cây dạng cỏ có gốc nạc.","Agapanthus Africanus L","Lá cây mọc dày và nhiều từ gốc rễ, xếp thành hai dãy, dạng hình dải gập nhiều hay ít, màu xanh lục thẫm. Lá cây dài khoảng 60 – 80cm, rộng khoảng 4 – 5cm, phiến lá dày, mặt lá nhẵn và bóng, gân chính nổi rõ, mép lá nguyên."},
          {"Xác Pháo Đỏ","xacphaodo","Loài hoa này có nguồn gốc từ khu vực Nam Mỹ, với màu đỏ đặc sắc vốn có, người dân địa phương nơi đây thường thích trồng chúng trong chậu hoặc thành từng thảm lớn ở các công viên hay vườn hoa để trang trí. ","Salvia splendens ker","Hoa xô đỏ nằm trong dòng họ thân bụi, có chiều cao trung bình từ 40 đến 60 cm, có đặc tính phân thành nhiều cành. Lá cây có hình bầu dục hoặc hình trái tim, màu xanh nhạt, mọc đối nhau, đặc biệt thuôn nhọn dần về phía đỉnh. "},
          {"Đỗ Quyên","doquyen","Cây hoa đỗ quyên còn gọi là cây sơn trà hoa, sơn thạch lựu hay mãn sơn hồng, ánh sơn hồng, báo xuân hoa, sơn thạch lựu","Rhododendron spp","Cây có dạng thân gỗ khẳng khiu, cao khoảng 0,5 - 2m, dáng cây phong trần, vỏ sần sùi và sống được khá lâu năm"},
  };


}
